name: CI

on:
  push: [main]

jobs:
  bulid-and-deploy:
    runs-on: ubuntu-latest,
    setps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build
      run: |
        npm install
        npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
